# backend/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: irshad04/backend:latest
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        ports:
        - containerPort: 3000
---
# backend/k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ecommerce

spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
